# Generated by Django 6.0.3 on 2026-03-25 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('banco', models.CharField(choices=[('BANCOESTADO', 'BancoEstado'), ('BCI', 'BCI'), ('SANTANDER', 'Santander'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_cuenta', models.CharField(choices=[('VISTA', 'Cuenta Vista'), ('CORRIENTE', 'Cuenta Corriente'), ('CHEQUERA', 'Chequera Electrónica'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_usuario_alke', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_destino', to=settings.AUTH_USER_MODEL)),
                ('usuario_alke_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_destino_alke', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('transferencia', 'Transferencia')], default='transferencia', max_length=20)),
                ('monto', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_recibidas', to='wallet.cuentadestino')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
